runtime: python27
api_version: 1
threadsafe: true
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?\..*$

libraries:
 - name: webapp2
   version: latest
 - name: jinja2
   version: latest

handlers:
 - url: /static
   static_dir: src/static
   secure: always
 - url: /admin/.*
   script: admin.app
   login: admin
   secure: always
 - url: /_ah/queue/deferred
   script: google.appengine.ext.deferred.deferred.application
   login: admin
 - url: /.*
   script: cubingusa.app
   secure: always
